Sub Example_DisplayOLEScale()
    ' This example reads and modifies the preference value that controls
    ' whether the OLE scaling dialog is displayed when OLE objects are
    ' inserted into a drawing.
    ' When finished, this example resets the preference value back to
    ' its original value.
    
    Dim ACADPref As AcadPreferencesSystem
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the system preferences object
    Set ACADPref = ThisDrawing.Application.preferences.System
    
    ' Read and display the original value
    originalValue = ACADPref.DisplayOLEScale
    MsgBox "The DisplayOLEScale preference is set to: " & originalValue

    ' Modify the DisplayOLEScale preference by toggling the value
    ACADPref.DisplayOLEScale = Not (ACADPref.DisplayOLEScale)
    newValue = ACADPref.DisplayOLEScale
    MsgBox "The DisplayOLEScale preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.DisplayOLEScale = originalValue
    MsgBox "The DisplayOLEScale preference was reset back to: " & originalValue
End Sub
