Sub Example_GripColorUnselected()
    ' This example reads and modifies the preference value that controls
    ' the color of unselected grips.
    ' When finished, this example resets the preference value back to
    ' its original value.
    
    Dim ACADPref As AcadPreferencesSelection
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the selection preferences object
    Set ACADPref = ThisDrawing.Application.preferences.Selection
    
    ' Read and display the original value
    originalValue = ACADPref.GripColorUnselected
    MsgBox "The GripColorUnselected preference is set to: " & originalValue

    ' Modify the GripColorUnselected preference by setting it to green
    ACADPref.GripColorUnselected = acGreen
    newValue = ACADPref.GripColorUnselected
    MsgBox "The GripColorUnselected preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.GripColorUnselected = originalValue
    MsgBox "The GripColorUnselected preference was reset back to: " & originalValue
End Sub
