Sub Example_AutoSnapAperture()
    ' This example reads and modifies the preference value that controls
    ' the display of the AutoSnap aperture.
    ' When finished, this example resets the preference value back to
    ' its original value.
    
    Dim ACADPref As AcadPreferencesDrafting
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the drafting preferences object
    Set ACADPref = ThisDrawing.Application.preferences.Drafting
    
    ' Read and display the original value
    originalValue = ACADPref.AutoSnapAperture
    MsgBox "The AutoSnapAperture preference is set to: " & originalValue

    ' Modify the AutoSnapAperture preference by toggling the value
    ACADPref.AutoSnapAperture = Not (originalValue)
    newValue = ACADPref.AutoSnapAperture
    MsgBox "The AutoSnapAperture preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.AutoSnapAperture = originalValue
    MsgBox "The AutoSnapAperture preference was reset back to: " & originalValue
End Sub
