Sub Example_FullCRCValidation()
    ' This example returns the current setting of
    ' FullCRCValidation. It then changes the value, and finally
    ' it resets the value back to the original setting.
    
    Dim preferences As AcadPreferences
    Dim currFullCRCValidation As Boolean
    
    Set preferences = ThisDrawing.Application.preferences
    
    ' Retrieve the current FullCRCValidation value
    currFullCRCValidation = preferences.OpenSave.FullCRCValidation
    MsgBox "The current value for FullCRCValidation is " & preferences.OpenSave.FullCRCValidation, vbInformation, "FullCRCValidation Example"
    
    ' Change the value for FullCRCValidation
    preferences.OpenSave.FullCRCValidation = Not (currFullCRCValidation)
    MsgBox "The new value for FullCRCValidation is " & preferences.OpenSave.FullCRCValidation, vbInformation, "FullCRCValidation Example"
    
    ' Reset FullCRCValidation to its original value
    preferences.OpenSave.FullCRCValidation = currFullCRCValidation
    MsgBox "The FullCRCValidation value is reset to " & preferences.OpenSave.FullCRCValidation, vbInformation, "FullCRCValidation Example"
End Sub
