Sub Example_LineSpacingStyle()
    ' This example creates an MText object in model space
    ' and then finds the LineSpacingStyle for the object.
    
    Dim MTextObj As AcadMText
    Dim corner(0 To 2) As Double
    Dim width As Double
    Dim text As String
    corner(0) = 0#: corner(1) = 10#: corner(2) = 0#
    width = 10
    text = "This is the text String for the mtext Object"

    ' Creates the mtext Object
    Set MTextObj = ThisDrawing.ModelSpace.AddMText(corner, width, text)
    ZoomAll
    
    ' Find the current LineSpacingStyle
    Dim currStyle As Integer
    currStyle = MTextObj.LineSpacingStyle
    MsgBox "The LineSpacingStyle for the MText object is: " & currStyle
    
    ' Change the LineSpacingStyle
    MTextObj.LineSpacingStyle = acLineSpacingStyleExactly
    MsgBox "The LineSpacingStyle for the MText object is: " & MTextObj.LineSpacingStyle
    
    ' Reset the LineSpacingStyle
    MTextObj.LineSpacingStyle = currStyle
    MsgBox "The LineSpacingStyle for the MText object is: " & MTextObj.LineSpacingStyle
    
End Sub
