Sub Example_AutoSnapMarker()
    ' This example reads and modifies the preference value that controls
    ' the AutoSnap marker.  When finished, this example resets the
    ' preference value back to its original value.
    
    Dim ACADPref As AcadPreferencesDrafting
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the drafting preferences object
    Set ACADPref = ThisDrawing.Application.preferences.Drafting
    
    ' Read and display the original value
    originalValue = ACADPref.AutoSnapMarker
    MsgBox "The AutoSnapMarker preference is set to: " & originalValue

    ' Modify the AutoSnapMarker preference by toggling the value
    ACADPref.AutoSnapMarker = Not (originalValue)
    newValue = ACADPref.AutoSnapMarker
    MsgBox "The AutoSnapMarker preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.AutoSnapMarker = originalValue
    MsgBox "The AutoSnapMarker preference was reset back to: " & originalValue
End Sub
