Sub Example_GripSize()
    ' This example reads and modifies the preference value that controls
    ' the size of grips. When finished, this example resets the
    ' preference value back to its original value.
    
    Dim ACADPref As AcadPreferencesSelection
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the selection preferences object
    Set ACADPref = ThisDrawing.Application.preferences.Selection
    
    ' Read and display the original value
    originalValue = ACADPref.GripSize
    MsgBox "The GripSize preference is set to: " & originalValue

    ' Modify the GripSize preference by setting it to 5
    ACADPref.GripSize = 5
    newValue = ACADPref.GripSize
    MsgBox "The GripSize preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.GripSize = originalValue
    MsgBox "The GripSize preference was reset back to: " & originalValue
End Sub
