Sub Example_DefaultPlotStyleForLayer()
    ' This example reads and modifies the preference value that controls
    ' the default plot style assigned to layers.
    ' When finished, this example resets the preference value back to
    ' its original value.
    
    Dim ACADPref As AcadPreferencesOutput
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the output preferences object
    Set ACADPref = ThisDrawing.Application.preferences.Output
    
    ' Read and display the original value
    originalValue = ACADPref.DefaultPlotStyleForLayer
    MsgBox "The DefaultPlotStyleForLayer preference is: " & originalValue

    ' Toggle and display the DefaultPlotStyleForLayer preference
    If ACADPref.DefaultPlotStyleForLayer = "ByBlock" Then
        ACADPref.DefaultPlotStyleForLayer = "Normal"
    Else
        ACADPref.DefaultPlotStyleForLayer = "ByBlock"
    End If

    newValue = ACADPref.DefaultPlotStyleForLayer
    MsgBox "The DefaultPlotStyleForLayer preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.DefaultPlotStyleForLayer = originalValue
    MsgBox "The DefaultPlotStyleForLayer preference was reset back to: " & originalValue
End Sub
