Sub Example_GripColorSelected()
    ' This example reads and modifies the preference value that controls
    ' the color of selected grips.
    ' When finished, this example resets the preference value back to
    ' its original value.
    
    Dim ACADPref As AcadPreferencesSelection
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the selection preferences object
    Set ACADPref = ThisDrawing.Application.preferences.Selection
    
    ' Read and display the original value
    originalValue = ACADPref.GripColorSelected
    MsgBox "The GripColorSelected preference is set to: " & originalValue

    ' Modify the GripColorSelected preference by setting it to green
    ACADPref.GripColorSelected = acGreen
    newValue = ACADPref.GripColorSelected
    MsgBox "The GripColorSelected preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.GripColorSelected = originalValue
    MsgBox "The GripColorSelected preference was reset back to: " & originalValue
End Sub
