Sub Example_Clipped()
    ' This example scans the current drawing paper space Viewports
    ' and displays whether or not any of them are clipped.
    
    Dim pviewportObj As Object
    Dim msg As String, ClippedState As String
    
    ' Make sure this drawing contains paper space viewports before continuing
    If ThisDrawing.PaperSpace.count = 0 Then
        MsgBox "There are no paper space viewports in the current drawing."
        Exit Sub
    End If
    
    ' Go through each PViewport object in the drawing paper space
    ' and determine whether the paper space viewport is clipped or not
    
    For Each pviewportObj In ThisDrawing.PaperSpace
        
        ' Determine if this is a paper space viewport
        If TypeName(pviewportObj) = "IAcadPViewport" Then
            
            ' Determine if this paper space viewport is clipped
            ClippedState = IIf(pviewportObj.Clipped, " is clipped", " is not clipped")
            msg = msg & "PViewport ID " & pviewportObj.objectID & ClippedState & vbCrLf
        
        End If
    
    Next

    ' Display clipped state of paper space Viewports
    MsgBox msg
End Sub
