Sub Example_PickDrag()
    ' This example reads and modifies the preference value that controls
    ' the method of drawing a selection window.
    ' When finished, this example resets the preference value back to
    ' its original value.
    
    Dim ACADPref As AcadPreferencesSelection
    Dim originalValue As Variant, newValue As Variant
    
    ' Get the selection preferences object
    Set ACADPref = ThisDrawing.Application.preferences.Selection
    
    ' Read and display the original value
    originalValue = ACADPref.PickDrag
    MsgBox "The PickDrag preference is set to: " & originalValue

    ' Modify the PickDrag preference by toggling the value
    ACADPref.PickDrag = Not (ACADPref.PickDrag)
    newValue = ACADPref.PickDrag
    MsgBox "The PickDrag preference has been set to: " & newValue

    ' Reset the preference back to its original value
    '
    ' * Note: Comment out this last section to leave the change to
    '         this preference in effect
    ACADPref.PickDrag = originalValue
    MsgBox "The PickDrag preference was reset back to: " & originalValue
End Sub
