Public Property Get EngCadEntityNametoString(EngCadEntityName) As String
Dim v As Variant
v = Array("AcDb2dPolyline", "AcDb3dFace", "AcDb3dPolyline", "AcDb3dSolid", "AcDbArc", "AcDbAttribute", "AcDbAttributeReference", "AcDbBlockReference", "AcDbCircle", "AcDbDgnUnderlay", "AcDbDim3PointAngular", "AcDbDimAligned", "AcDbDimAngular", "AcDbDimArcLength", "AcDbDimDiametric", "AcDbDimOrdinate", "AcDbDimRadial", "AcDbDimRadialLarge", "AcDbDimRotated", "AcDbDwfUnderlay", "AcDbEllipse", "AcDbExternalReference", "AcDbHatch", "AcDbLeader", "AcDbLine", "AcDbMInsertBlock", "AcDbMLeader", "AcDbMLine", "AcDbMtext", "AcDbNurbSurface", "AcDbPdfUnderlay", "AcDbPoint", "AcDbPolyfaceMesh", "AcDbPolymesh", "AcDbPolyline", "AcDbPViewport", "AcDbRaster", "AcDbRay", "AcDbRegion", "AcDbShape", "AcDbSolid", "AcDbSpline", "AcDbSubDMesh", "AcDbTable", "AcDbText", "AcDbTolerance", "AcDbTrace", "AcDbXline")
EngCadEntityNametoString = VBA.CStr(v(EngCadEntityName))
End Property
